__author__ = 'Salem'
import time
from tqdm import tqdm
import time
import sys


print("===========================================================================")
print("=====================   WELCOME TO SOBU  ==================================")
print("===========================   TOOLS   =====================================")
print("===========================================================================")
print("TOOL BY skali1144")









print("Running sobu.py/setup.py")
time.sleep(3)

toolbar_width = 40

# setup toolbar
sys.stdout.write("[%s]" % (" " * toolbar_width))
sys.stdout.flush()
sys.stdout.write("\b" * (toolbar_width+1)) # return to start of line, after '['

for i in range(toolbar_width):
    time.sleep(0.1) # do real work here
    # update the bar
    sys.stdout.write("-")
    sys.stdout.flush()
time.sleep(0.1)
sys.stdout.write("]\n") # this ends the progress bar
print("1/3")

toolbar_width = 40
time.sleep(2)

# setup toolbar
sys.stdout.write("[%s]" % (" " * toolbar_width))
sys.stdout.flush()
sys.stdout.write("\b" * (toolbar_width+1)) # return to start of line, after '['

for i in range(toolbar_width):
    time.sleep(0.1) # do real work here
    # update the bar
    sys.stdout.write("-")
    sys.stdout.flush()

sys.stdout.write("]\n") # this ends the progress bar
print("2/3")

toolbar_width = 40
time.sleep(2)

# setup toolbar
sys.stdout.write("[%s]" % (" " * toolbar_width))
sys.stdout.flush()
sys.stdout.write("\b" * (toolbar_width+1)) # return to start of line, after '['

for i in range(toolbar_width):
    time.sleep(0.1) # do real work here
    # update the bar
    sys.stdout.write("-")
    sys.stdout.flush()

sys.stdout.write("]\n") # this ends the progress bar
print("3/3")
toolbar_width = 40
time.sleep(2)

# setup toolbar
sys.stdout.write("[%s]" % (" " * toolbar_width))
sys.stdout.flush()
sys.stdout.write("\b" * (toolbar_width+1)) # return to start of line, after '['

for i in range(toolbar_width):
    time.sleep(0.1) # do real work here
    # update the bar
    sys.stdout.write("-")
    sys.stdout.flush()

sys.stdout.write("]\n") # this ends the progress bar
print("Done.")
time.sleep(5)




print("…………..$……………………………………..$…………..")
print("…………$$……………………………………..$$…………")
print("…………$$……………………………………..$$…………")
print("…………..$$s………………………………s$$…………..")
print("…………….$$$$……………………….$$$$…………….")
print("………………³$$$$..¶¶¶¶¶¶¶¶..$$$$³………………")
print("………………..³$$$$..¶¶¶¶¶¶..$$$$³………………..")
print("………………¶..$$$$$..¶¶¶¶..$$$$$..¶………………")
print("…………….¶¶¶..$$$..¶¶¶¶¶¶..$$$..¶¶………………")
print("…………….¶¶¶….¶¶¶¶¶¶¶¶¶¶….¶¶¶¶………………")
print("…………….¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶………………")
print("………………..¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶………………..")
print("………………..¶¶……..¶¶¶¶……….¶¶………………….")
print("………………..¶¶¶¶¶¶¶¶..¶¶¶¶¶¶¶¶………………….")
print("………………….¶¶¶¶¶¶……¶¶¶¶¶¶¶………………….")
print("……………………….¶¶¶¶¶¶¶¶¶…………………………")
print("……………………….¶..¶..¶..¶..¶……………………")
print("…………¶…………..¶…………..¶…………..¶…………..")
print("……….¶¶……………………………………….¶¶…………")
print("……….¶¶……………………………………….¶¶…………")
print("……….¶¶…………..¶¶……….¶¶…………..¶¶…………")
print("……….¶¶..¶¶..¶¶..¶…………..¶..¶¶..¶¶..¶¶…………")
print("……¶..¶¶..¶¶..¶¶..¶…………..¶..¶¶..¶¶..¶¶..¶……..")
print("….¶¶..¶¶..¶¶..¶¶..¶…………..¶..¶¶..¶¶..¶¶..¶¶……")
print("……¶¶¶¶..¶¶..¶¶………………….¶¶..¶¶..¶¶¶¶……..")

print("Choose one of the Tool=====>>>>     1).WIFI Password Searcher  |   2).Help  |   3).Random Data           4).Drawings")
print(":")
user_name = input()

if user_name == "2":
    while 3 > 2:
        print("Welcome to help center here we help you all about educatonal purpose tool for more help please visit (https://saialhmadi.wixsite.com/salem)")
        break
elif user_name == "1":
    if user_name == "1":
        for i in tqdm(range(3)):
            time.sleep(3)
            
                
for i in tqdm(range(2)):
                time.sleep(2)
            

                for i in tqdm(range(1)):
                    time.sleep(1)

print("Done.")

if user_name == "1":
                time.sleep(5)
                print("                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             ")
if user_name == "1":    print("=======================================================================")
if user_name == "1":    print("============================== SHOW DRIVERS ===========================")
if user_name == "1":    print("=======================================================================")
if user_name == "1":
    if user_name == "1":
        if user_name == "1":    print("Interface name: Wi-Fi")
if user_name == "1":
    if user_name == "1":    print("Driver                    : Intel(R) Wi-Fi 6 AX200 160MHz")
if user_name == "1":    print("Vendor                    : Intel Corporation")
if user_name == "1":    print("Provider                  : Intel")
if user_name == "1":    print("Date                      : 1/2/2022")
if user_name == "1":    print(" Version                   : 22.110.1.1")
if user_name == "1":    print(" INFfile                  : oem47.inf")
if user_name == "1":    print("Type                      : Native Wi-Fi Driver")
if user_name == "1":    print("Radio types supported     : 802.11b 802.11g 802.11n 802.11a 802.11ac 802.11ax")
if user_name == "1":    print("FIPS 140-2 mode supported : Yes")
if user_name == "1":    print("802.11w Management Frame Protection supported : Yes")
if user_name == "1":    print("Hosted network supported  : No")
if user_name == "1":    print("Authentication and cipher supported in infrastructure mode:")
if user_name == "1":    print("                            Open             None")
if user_name == "1":    print("                            Open             WEP-40bit")
if user_name == "1":    print("                            Open             WEP-104bit")
if user_name == "1":    print("                            Open             WEP")
if user_name == "1":    print("                            WPA-Enterprise   TKIP")
if user_name == "1":    print("                            WPA-Enterprise   CCMP")
if user_name == "1":    print("                            WPA-Personal     TKIP")
if user_name == "1":    print("                            WPA-Personal     CCMP")
if user_name == "1":    print("                            WPA2-Enterprise  TKIP")
if user_name == "1":    print("                            WPA2-Enterprise  CCMP")
if user_name == "1":    print("                            WPA2-Personal    TKIP")
if user_name == "1":    print("                            WPA2-Personal    CCMP")
if user_name == "1":    print("                            Open             Vendor defined")
if user_name == "1":    print("                            WPA3-Personal    CCMP")
if user_name == "1":    print("                            Vendor defined   Vendor defined")
if user_name == "1":    print("                            WPA3-Enterprise 192 Bits GCMP-256")
if user_name == "1":    print("                            OWE              CCMP")
if user_name == "1":    print("Number of supported bands : 2")
if user_name == "1":    print("                            2.4 GHz [ 0 MHz - 0 MHz]")
if user_name == "1":    print("                            5 GHz   [ 0 MHz - 0 MHz]")
if user_name == "1":    print("IHV service present       : Yes")
if user_name == "1":    print("IHV adapter OUI           : [00 00 00], type: [00]")
if user_name == "1":    print("IHV extensibility DLL path: C:\WINDOWS\system32\IntelIHVRouter08.dll")
if user_name == "1":    print("IHV UI extensibility ClSID: {00000000-0000-0000-0000-000000000000}")
if user_name == "1":    print("IHV diagnostics CLSID     : {00000000-0000-0000-0000-000000000000}")
if user_name == "1":    print("Wireless Display Supported: Yes (Graphics Driver: Yes, Wi-Fi Driver: Yes")
time.sleep(5)
if user_name == "1":print("=======================================================================")
if user_name == "1":print("============================= SHOW INTERFACES =========================")
if user_name == "1":print("=======================================================================")
if user_name == "1":
    if user_name == "1":print("There is 1 interface on the system:")
if user_name == "1":
    if user_name == "1":print("    Name                   : Wi-Fi")
if user_name == "1":print("    Description            : Intel(R) Wi-Fi 6 AX200 160MHz")
if user_name == "1":print("    GUID                   : 611f4971-0997-4b2a-b252-47117b63cda8")
if user_name == "1":print("    Physical address       : 6e:ec:3c:75:47:12")
if user_name == "1":print("    Interface type         : Primary")
if user_name == "1":print("    State                  : connected")
if user_name == "1":print("    SSID                   : BuSultan2")
if user_name == "1":print("    BSSID                  : ee:ad:e0:2f:f8:ba")
if user_name == "1":print("    Network type           : Infrastructure")
if user_name == "1":print("    Radio type             : 802.11n")
if user_name == "1":print("    Authentication         : WPA2-Personal")
if user_name == "1":print("    Cipher                 : CCMP")
if user_name == "1":print("    Connection mode        : Auto Connect")
if user_name == "1":print("    Band                   : 2.4 GHz")
if user_name == "1":print("    Channel                : 2")
if user_name == "1":print("    Receive rate (Mbps)    : 104")
if user_name == "1":print("    Transmit rate (Mbps)   : 72.2")
if user_name == "1":print("    Signal                 : 82%")
if user_name == "1":print("    Profile                : BuSultan2")
if user_name == "1":print("    Hosted network status  : Not available")
if user_name == "1":
  if user_name == "1":
    if user_name == "1":print("=======================================================================")
if user_name == "1":print("=========================== SHOW HOSTED NETWORK =======================")
if user_name == "1":print("=======================================================================")
time.sleep(5)
if user_name == "1":print("")
if user_name == "1":print("")
if user_name == "1":print("Hosted network settings")
if user_name == "1":print("-----------------------")
if user_name == "1":print("    Mode                   : Allowed")
if user_name == "1":print("    Settings               : <Not configured>")
if user_name == "1":print("")
if user_name == "1":print("Hosted network status")
if user_name == "1":print("---------------------")
if user_name == "1":print("    Status                 : Not available")
if user_name == "1":print("")
if user_name == "1":print("")
if user_name == "1":print("=======================================================================")
if user_name == "1":print("============================= SHOW SETTINGS ===========================")
if user_name == "1":print("=======================================================================")
time.sleep(5)
if user_name == "1":print("")
if user_name == "1":print("")
if user_name == "1":print("Wireless LAN settings")
if user_name == "1":print("---------------------")
if user_name == "1":print("    Show blocked networks in visible network list: No")
if user_name == "1":print("")
if user_name == "1":print("    Only use GP profiles on GP-configured networks: No")
if user_name == "1":print("")
if user_name == "1":print("    Hosted network mode allowed in WLAN service: Yes")
if user_name == "1":print("")
if user_name == "1":print("    Allow shared user credentials for network authentication: Yes")
if user_name == "1":print("")
if user_name == "1":print("    Block period: Not Configured.")
if user_name == "1":print("")
if user_name == "1":print("    Auto configuration logic is enabled on interface Wi-Fi")
if user_name == "1":print("    MAC randomization enabled on interface Wi-Fi")
if user_name == "1":print("")
if user_name == "1":print("")
if user_name == "1":print("=======================================================================")
if user_name == "1":print("============================== SHOW FILTERS ===========================")
if user_name == "1":print("=======================================================================")
time.sleep(5)
if user_name == "1":print("")
if user_name == "1":print("")
if user_name == "1":print("Allow list on the system (group policy)")
if user_name == "1":print("---------------------------------------")
if user_name == "1":print("    <None>")
if user_name == "1":print("")
if user_name == "1":print("Allow list on the system (user)")
if user_name == "1":print("-------------------------------")
if user_name == "1":print("    <None>")
if user_name == "1":print("")
if user_name == "1":print("Block list on the system (group policy)")
if user_name == "1":print("---------------------------------------")
if user_name == "1":print("    <None>")
if user_name == "1":print("")
if user_name == "1":print("Block list on the system (user)")
if user_name == "1":print("-------------------------------")
if user_name == "1":print("    <None>")
if user_name == "1":print("")
if user_name == "1":print("")
if user_name == "1":print("=======================================================================")
if user_name == "1":print("=========================== SHOW CREATEALLUSER ========================")
if user_name == "1":print("=======================================================================")
time.sleep(5)
if user_name == "1":print("")
if user_name == "1":print("")
if user_name == "1":print("Everyone is allowed to create all user profiles.")
if user_name == "1":print("")
if user_name == "1":print("")
if user_name == "1":print("=======================================================================")
if user_name == "1":print("============================= SHOW PROFILES ===========================")
if user_name == "1":print("=======================================================================")
time.sleep(5)
if user_name == "1":print("")
if user_name == "1":print("")
if user_name == "1":print("Profiles on interface Wi-Fi:")
if user_name == "1":print("")
if user_name == "1":print("Group policy profiles (read only)")
if user_name == "1":print("---------------------------------")
if user_name == "1":print("    <None>")
if user_name == "1":print("")
if user_name == "1":print("User profiles")
if user_name == "1":print("-------------")
if user_name == "1":print("    All User Profile     : Salem's iPhone")
if user_name == "1":print("    All User Profile     : BuSultan2")
if user_name == "1":print("    All User Profile     : Ibrahim")
if user_name == "1":print("    All User Profile     : iPhone 11 Pro (2)")
if user_name == "1":print("    All User Profile     : DIS-Exams")
if user_name == "1":print("    All User Profile     : TAJ MAHAL")
if user_name == "1":print("    All User Profile     : Amari")
if user_name == "1":print("    All User Profile     : true_home2G_3bb")
if user_name == "1":print("")
if user_name == "1":print("")
if user_name == "1":print("=======================================================================")
if user_name == "1":print("========================== SHOW PROFILES NAMES ========================")
if user_name == "1":print("=======================================================================")
time.sleep(5)
if user_name == "1":print("")
if user_name == "1":print("")
if user_name == "1":print("Profile Salem's iPhone on interface Wi-Fi:")
if user_name == "1":print("=======================================================================")
if user_name == "1":print("")
if user_name == "1":print("Applied: All User Profile")
if user_name == "1":print("")
if user_name == "1":print("Profile information")
if user_name == "1":print("-------------------")
if user_name == "1":print("    Version                : 1")
if user_name == "1":print("    Type                   : Wireless LAN")
if user_name == "1":print("    Name                   : Salem's iPhone")
if user_name == "1":print("    Control options        :")
if user_name == "1":print("        Connection mode    : Connect automatically")
if user_name == "1":print("        Network broadcast  : Connect only if this network is broadcasting")
if user_name == "1":print("        AutoSwitch         : Do not switch to other networks")
if user_name == "1":print("        MAC Randomization  : Enabled")
if user_name == "1":print("")
if user_name == "1":print("Connectivity settings")
if user_name == "1":print("---------------------")
if user_name == "1":print("    Number of SSIDs        : 1")
if user_name == "1":print("    SSID name              : Salems iPhone")
if user_name == "1":print("    Network type           : Infrastructure")
if user_name == "1":print("    Radio type             : [ Any Radio Type ]")
if user_name == "1":print("    Vendor extension          : Not present")
if user_name == "1":print("")
if user_name == "1":print("Security settings")
if user_name == "1":print("-----------------")
if user_name == "1":print("    Authentication         : WPA3-Personal")
if user_name == "1":print("    Cipher                 : CCMP")
if user_name == "1":print("    Authentication         : WPA2-Personal")
if user_name == "1":print("    Cipher                 : CCMP")
if user_name == "1":print("    Authentication         : WPA3-Personal")
if user_name == "1":print("    Cipher                 : GCMP")
if user_name == "1":print("    Authentication         : WPA2-Personal")
if user_name == "1":print("    Cipher                 : GCMP")
if user_name == "1":print("    Security key           : Present")
if user_name == "1":print("")
if user_name == "1":print("Cost settings")
if user_name == "1":print("-------------")
if user_name == "1":print("    Cost                   : Unrestricted")
if user_name == "1":print("    Congested              : No")
if user_name == "1":print("    Approaching Data Limit : No")
if user_name == "1":print("    Over Data Limit        : No")
if user_name == "1":print("    Roaming                : No")
if user_name == "1":print("    Cost Source            : Default")
if user_name == "1":print("")
if user_name == "1":print("")
if user_name == "1":print("Profile BuSultan2 on interface Wi-Fi:")
if user_name == "1":print("=======================================================================")
if user_name == "1":print("")
if user_name == "1":print("Applied: All User Profile")
if user_name == "1":print("")
if user_name == "1":print("Profile information")
if user_name == "1":print("-------------------")
if user_name == "1":print("    Version                : 1")
if user_name == "1":print("    Type                   : Wireless LAN")
if user_name == "1":print("    Name                   : BuSultan2")
if user_name == "1":print("    Control options        :")
if user_name == "1":print("        Connection mode    : Connect automatically")
if user_name == "1":print("        Network broadcast  : Connect only if this network is broadcasting")
if user_name == "1":print("        AutoSwitch         : Do not switch to other networks")
if user_name == "1":print("        MAC Randomization  : Enabled")
if user_name == "1":print("")
if user_name == "1":print("Connectivity settings")
if user_name == "1":print("---------------------")
if user_name == "1":print("    Number of SSIDs        : 1")
if user_name == "1":print("    SSID name              : BuSultan2")
if user_name == "1":print("    Network type           : Infrastructure")
if user_name == "1":print("    Radio type             : [ Any Radio Type ]")
if user_name == "1":print("    Vendor extension          : Not present")
if user_name == "1":print("")
if user_name == "1":print("Security settings")
if user_name == "1":print("-----------------")
if user_name == "1":print("    Authentication         : WPA2-Personal")
if user_name == "1":print("    Cipher                 : CCMP")
if user_name == "1":print("    Authentication         : WPA2-Personal")
if user_name == "1":print("    Cipher                 : GCMP")
if user_name == "1":print("    Security key           : Present")
if user_name == "1":print("")
if user_name == "1":print("Cost settings")
if user_name == "1":print("-------------")
if user_name == "1":print("    Cost                   : Unrestricted")
if user_name == "1":print("    Congested              : No")
if user_name == "1":print("    Approaching Data Limit : No")
if user_name == "1":print("    Over Data Limit        : No")
if user_name == "1":print("    Roaming                : No")
if user_name == "1":print("    Cost Source            : Default")
if user_name == "1":print("")
if user_name == "1":print("")
if user_name == "1":print("Profile Ibrahim on interface Wi-Fi:")
if user_name == "1":print("=======================================================================")
if user_name == "1":print("")
if user_name == "1":print("Applied: All User Profile")
if user_name == "1":print("")
if user_name == "1":print("Profile information")
if user_name == "1":print("-------------------")
if user_name == "1":print("    Version                : 1")
if user_name == "1":print("    Type                   : Wireless LAN")
if user_name == "1":print("    Name                   : Ibrahim")
if user_name == "1":print("    Control options        :")
if user_name == "1":print("        Connection mode    : Connect automatically")
if user_name == "1":print("        Network broadcast  : Connect only if this network is broadcasting")
if user_name == "1":print("        AutoSwitch         : Do not switch to other networks")
if user_name == "1":print("        MAC Randomization  : Disabled")
if user_name == "1":print("")
if user_name == "1":print("Connectivity settings")
if user_name == "1":print("---------------------")
if user_name == "1":print("    Number of SSIDs        : 1")
if user_name == "1":print("    SSID name              : Ibrahim")
if user_name == "1":print("    Network type           : Infrastructure")
if user_name == "1":print("    Radio type             : [ Any Radio Type ]")
if user_name == "1":print("    Vendor extension          : Not present")
if user_name == "1":print("")
if user_name == "1":print("Security settings")
if user_name == "1":print("-----------------")
if user_name == "1":print("    Authentication         : WPA2-Personal")
if user_name == "1":print("    Cipher                 : CCMP")
if user_name == "1":print("    Authentication         : WPA2-Personal")
if user_name == "1":print("    Cipher                 : GCMP")
if user_name == "1":print("    Security key           : Present")
if user_name == "1":print("")
if user_name == "1":print("Cost settings")
if user_name == "1":print("-------------")
if user_name == "1":print("    Cost                   : Unrestricted")
if user_name == "1":print("    Congested              : No")
if user_name == "1":print("    Approaching Data Limit : No")
if user_name == "1":print("    Over Data Limit        : No")
if user_name == "1":print("    Roaming                : No")
if user_name == "1":print("    Cost Source            : Default")
if user_name == "1":print("")
if user_name == "1":print("")
if user_name == "1":print("Profile iPhone 11 Pro (2) on interface Wi-Fi:")
if user_name == "1":print("=======================================================================")
if user_name == "1":print("")
if user_name == "1":print("Applied: All User Profile")
if user_name == "1":print("")
if user_name == "1":print("Profile information")
if user_name == "1":print("-------------------")
if user_name == "1":print("    Version                : 1")
if user_name == "1":print("    Type                   : Wireless LAN")
if user_name == "1":print("    Name                   : iPhone 11 Pro (2)")
if user_name == "1":print("    Control options        :")
if user_name == "1":print("        Connection mode    : Connect automatically")
if user_name == "1":print("        Network broadcast  : Connect only if this network is broadcasting")
if user_name == "1":print("        AutoSwitch         : Do not switch to other networks")
if user_name == "1":print("        MAC Randomization  : Disabled")
if user_name == "1":print("")
if user_name == "1":print("Connectivity settings")
if user_name == "1":print("---------------------")
if user_name == "1":print("    Number of SSIDs        : 1")
if user_name == "1":print("    SSID name              : iPhone 11 Pro 2")
if user_name == "1":print("    Network type           : Infrastructure")
if user_name == "1":print("    Radio type             : [ Any Radio Type ]")
if user_name == "1":print("    Vendor extension          : Not present")
if user_name == "1":print("")
if user_name == "1":print("Security settings")
if user_name == "1":print("-----------------")
if user_name == "1":print("    Authentication         : WPA3-Personal")
if user_name == "1":print("    Cipher                 : CCMP")
if user_name == "1":print("    Authentication         : WPA2-Personal")
if user_name == "1":print("    Cipher                 : CCMP")
if user_name == "1":print("    Authentication         : WPA3-Personal")
if user_name == "1":print("    Cipher                 : GCMP")
if user_name == "1":print("    Authentication         : WPA2-Personal")
if user_name == "1":print("    Cipher                 : GCMP")
if user_name == "1":print("    Security key           : Present")
if user_name == "1":print("")
if user_name == "1":print("Cost settings")
if user_name == "1":print("-------------")
if user_name == "1":print("    Cost                   : Unrestricted")
if user_name == "1":print("    Congested              : No")
if user_name == "1":print("    Approaching Data Limit : No")
if user_name == "1":print("    Over Data Limit        : No")
if user_name == "1":print("    Roaming                : No")
if user_name == "1":print("    Cost Source            : Default")
if user_name == "1":print("")
if user_name == "1":print("")
if user_name == "1":print("Profile DIS-Exams on interface Wi-Fi:")
if user_name == "1":print("=======================================================================")
if user_name == "1":print("")
if user_name == "1":print("Applied: All User Profile")
if user_name == "1":print("")
if user_name == "1":print("Profile information")
if user_name == "1":print("-------------------")
if user_name == "1":print("    Version                : 1")
if user_name == "1":print("    Type                   : Wireless LAN")
if user_name == "1":print("    Name                   : DIS-Exams")
if user_name == "1":print("    Control options        :")
if user_name == "1":print("        Connection mode    : Connect automatically")
if user_name == "1":print("        Network broadcast  : Connect only if this network is broadcasting")
if user_name == "1":print("        AutoSwitch         : Do not switch to other networks")
if user_name == "1":print("        MAC Randomization  : Enabled")
if user_name == "1":print("")
if user_name == "1":print("Connectivity settings")
if user_name == "1":print("---------------------")
if user_name == "1":print("    Number of SSIDs        : 1")
if user_name == "1":print("    SSID name              : DIS-Exams")
if user_name == "1":print("    Network type           : Infrastructure")
if user_name == "1":print("    Radio type             : [ Any Radio Type ]")
if user_name == "1":print("    Vendor extension          : Not present")
if user_name == "1":print("")
if user_name == "1":print("Security settings")
if user_name == "1":print("-----------------")
if user_name == "1":print("    Authentication         : WPA2-Personal")
if user_name == "1":print("    Cipher                 : CCMP")
if user_name == "1":print("    Authentication         : WPA2-Personal")
if user_name == "1":print("    Cipher                 : GCMP")
if user_name == "1":print("    Security key           : Present")
if user_name == "1":print("")
if user_name == "1":print("Cost settings")
if user_name == "1":print("-------------")
if user_name == "1":print("    Cost                   : Fixed")
if user_name == "1":print("    Congested              : No")
if user_name == "1":print("    Approaching Data Limit : No")
if user_name == "1":print("    Over Data Limit        : No")
if user_name == "1":print("    Roaming                : No")
if user_name == "1":print("    Cost Source            : User")
if user_name == "1":print("")
if user_name == "1":print("")
if user_name == "1":print("Profile TAJ MAHAL on interface Wi-Fi:")
if user_name == "1":print("=======================================================================")
if user_name == "1":print("")
if user_name == "1":print("Applied: All User Profile")
if user_name == "1":print("")
if user_name == "1":print("Profile information")
if user_name == "1":print("-------------------")
if user_name == "1":print("    Version                : 1")
if user_name == "1":print("    Type                   : Wireless LAN")
if user_name == "1":print("    Name                   : TAJ MAHAL")
if user_name == "1":print("    Control options        :")
if user_name == "1":print("        Connection mode    : Connect manually")
if user_name == "1":print("        Network broadcast  : Connect only if this network is broadcasting")
if user_name == "1":print("        AutoSwitch         : Do not switch to other networks")
if user_name == "1":print("        MAC Randomization  : Disabled")
if user_name == "1":print("")
if user_name == "1":print("Connectivity settings")
if user_name == "1":print("---------------------")
if user_name == "1":print("    Number of SSIDs        : 1")
if user_name == "1":print("    SSID name              : TAJ MAHAL")
if user_name == "1":print("    Network type           : Infrastructure")
if user_name == "1":print("    Radio type             : [ Any Radio Type ]")
if user_name == "1":print("    Vendor extension          : Not present")
if user_name == "1":print("")
if user_name == "1":print("Security settings")
if user_name == "1":print("-----------------")
if user_name == "1":print("    Authentication         : Open")
if user_name == "1":print("    Cipher                 : None")
if user_name == "1":print("    Security key           : Absent")
if user_name == "1":print("    Key Index              : 1")
if user_name == "1":print("")
if user_name == "1":print("Cost settings")
if user_name == "1":print("-------------")
if user_name == "1":print("    Cost                   : Unrestricted")
if user_name == "1":print("    Congested              : No")
if user_name == "1":print("    Approaching Data Limit : No")
if user_name == "1":print("    Over Data Limit        : No")
if user_name == "1":print("    Roaming                : No")
if user_name == "1":print("    Cost Source            : Default")
if user_name == "1":print("")
if user_name == "1":print("")
if user_name == "1":print("Profile Amari on interface Wi-Fi:")
if user_name == "1":print("=======================================================================")
if user_name == "1":print("")
if user_name == "1":print("Applied: All User Profile")
if user_name == "1":print("")
if user_name == "1":print("Profile information")
if user_name == "1":print("-------------------")
if user_name == "1":print("    Version                : 1")
if user_name == "1":print("    Type                   : Wireless LAN")
if user_name == "1":print("    Name                   : Amari")
if user_name == "1":print("    Control options        :")
if user_name == "1":print("        Connection mode    : Connect automatically")
if user_name == "1":print("        Network broadcast  : Connect only if this network is broadcasting")
if user_name == "1":print("        AutoSwitch         : Do not switch to other networks")
if user_name == "1":print("        MAC Randomization  : Enabled")
if user_name == "1":print("")
if user_name == "1":print("Connectivity settings")
if user_name == "1":print("---------------------")
if user_name == "1":print("    Number of SSIDs        : 1")
if user_name == "1":print("    SSID name              : Amari")
if user_name == "1":print("    Network type           : Infrastructure")
if user_name == "1":print("    Radio type             : [ Any Radio Type ]")
if user_name == "1":print("    Vendor extension          : Not present")
if user_name == "1":print("")
if user_name == "1":print("Security settings")
if user_name == "1":print("-----------------")
if user_name == "1":print("    Authentication         : Open")
if user_name == "1":print("    Cipher                 : None")
if user_name == "1":print("    Security key           : Absent")
if user_name == "1":print("    Key Index              : 1")
if user_name == "1":print("")
if user_name == "1":print("Cost settings")
if user_name == "1":print("-------------")
if user_name == "1":print("    Cost                   : Unrestricted")
if user_name == "1":print("    Congested              : No")
if user_name == "1":print("    Approaching Data Limit : No")
if user_name == "1":print("    Over Data Limit        : No")
if user_name == "1":print("    Roaming                : No")
if user_name == "1":print("    Cost Source            : Default")
if user_name == "1":print("")
if user_name == "1":print("")
if user_name == "1":print("Profile true_home2G_3bb on interface Wi-Fi:")
if user_name == "1":print("=======================================================================")
if user_name == "1":print("")
if user_name == "1":print("Applied: All User Profile")
if user_name == "1":print("")
if user_name == "1":print("Profile information")
if user_name == "1":print("-------------------")
if user_name == "1":print("    Version                : 1")
if user_name == "1":print("    Type                   : Wireless LAN")
if user_name == "1":print("    Name                   : true_home2G_3bb")
if user_name == "1":print("    Control options        :")
if user_name == "1":print("        Connection mode    : Connect automatically")
if user_name == "1":print("        Network broadcast  : Connect only if this network is broadcasting")
if user_name == "1":print("        AutoSwitch         : Do not switch to other networks")
if user_name == "1":print("        MAC Randomization  : Disabled")
if user_name == "1":print("")
if user_name == "1":print("Connectivity settings")
if user_name == "1":print("---------------------")
if user_name == "1":print("    Number of SSIDs        : 1")
if user_name == "1":print("    SSID name              : true_home2G_3bb")
if user_name == "1":print("    Network type           : Infrastructure")
if user_name == "1":print("    Radio type             : [ Any Radio Type ]")
if user_name == "1":print("    Vendor extension          : Not present")
if user_name == "1":print("")
if user_name == "1":print("Security settings")
if user_name == "1":print("-----------------")
if user_name == "1":print("    Authentication         : WPA2-Personal")
if user_name == "1":print("    Cipher                 : CCMP")
if user_name == "1":print("    Authentication         : WPA2-Personal")
if user_name == "1":print("    Cipher                 : GCMP")
if user_name == "1":print("    Security key           : Present")
if user_name == "1":print("")
if user_name == "1":print("Cost settings")
if user_name == "1":print("-------------")
if user_name == "1":print("    Cost                   : Unrestricted")
if user_name == "1":print("    Congested              : No")
if user_name == "1":print("    Approaching Data Limit : No")
if user_name == "1":print("    Over Data Limit        : No")
if user_name == "1":print("    Roaming                : No")
if user_name == "1":print("    Cost Source            : Default")
if user_name == "1":print("")
if user_name == "1":print("")
if user_name == "1":print("=======================================================================")
if user_name == "1":print("======================= SHOW NETWORKS MODE=BSSID ======================")
if user_name == "1":print("=======================================================================")
if user_name == "1":print("")
if user_name == "1":print("")
if user_name == "1":print("Interface name : Wi-Fi")
if user_name == "1":print("There are 1 networks currently visible.")
if user_name == "1":print("")
if user_name == "1":print("SSID 1 : BuSultan2")
if user_name == "1":print("    Network type            : Infrastructure")
if user_name == "1":print("    Authentication          : WPA2-Personal")
if user_name == "1":print("    Encryption              : CCMP")
if user_name == "1":print("    BSSID 1                 : ee:ad:e0:2f:f8:ba")
if user_name == "1":print("         Signal             : 82%")
if user_name == "1":print("         Radio type         : 802.11ac")
if user_name == "1":print("         Band               : 2.4 GHz")
if user_name == "1":print("         Channel            : 2")
if user_name == "1":print("         Bss Load:")
if user_name == "1":print("             Connected Stations:         13")
if user_name == "1":print("             Channel Utilization:        13 (5 %)")
if user_name == "1":print("             Medium Available Capacity:  31250 (1000000 us/s)")
if user_name == "1":print("         Basic rates (Mbps) : 1 2 5.5 11")
if user_name == "1":print("         Other rates (Mbps) : 6 9 12 18 24 36 48 54")
if user_name == "1":print("")
if user_name == "1":print("")
if user_name == "1":print("=======================================================================")
if user_name == "1":print("======================= SHOW INTERFACE CAPABILITIES ===================")
if user_name == "1":print("=======================================================================")
time.sleep(5)
if user_name == "1":print("")
if user_name == "1":print("")
if user_name == "1":print("Wireless System Capabilities")
if user_name == "1":print("----------------------------")
if user_name == "1":print("    Number of antennas connected to the 802.11 radio (value not available)")
if user_name == "1":print("    Max number of channels the device can operate on, simultaneously (value not ava")
if user_name == "1":print("    Co-existence Support                        : Unknown")
if user_name == "1":print("")
if user_name == "1":print("")
if user_name == "1":print("Wireless Device Capabilities")
if user_name == "1":print("----------------------------")
if user_name == "1":print("")
if user_name == "1":print("Interface name: Wi-Fi")
if user_name == "1":print("")
if user_name == "1":print("    WDI Version (Windows)                       : 0.1.1.12")
if user_name == "1":print("    WDI Version (IHV)                           : 0.1.1.12")
if user_name == "1":print("    WiFiCx Version (IHV)                        : WiFiCx Interface Not Supported")
if user_name == "1":print("    Firmware Version                            : 64.23")
if user_name == "1":print("    Station                                     : Supported")
if user_name == "1":print("    Soft AP                                     : Not supported")
if user_name == "1":print("    Network monitor mode                        : Not supported")
if user_name == "1":print("    Wi-Fi Direct Device                         : Supported")
if user_name == "1":print("    Wi-Fi Direct GO                             : Supported")
if user_name == "1":print("    Wi-Fi Direct Client                         : Supported")
if user_name == "1":print("    Protected Management Frames                 : Supported")
if user_name == "1":print("    DOT11k neighbor report                      : Supported")
if user_name == "1":print("    ANQP Service Information Discovery          : Supported")
if user_name == "1":print("    Action Frame                                : Supported")
if user_name == "1":print("    Diversity Antenna                           : Supported")
if user_name == "1":print("    IBSS                                        : Not Supported")
if user_name == "1":print("    Promiscuous Mode                            : Not Supported")
if user_name == "1":print("    P2P Device Discovery                        : Supported")
if user_name == "1":print("    P2P Service Name Discovery                  : Supported")
if user_name == "1":print("    P2P Service Info Discovery                  : Not Supported")
if user_name == "1":print("    P2P Background Discovery                    : Supported")
if user_name == "1":print("    P2P GO on 5 GHz                             : Supported")
if user_name == "1":print("    ASP 2.0 Service Name Discovery              : Not Supported")
if user_name == "1":print("    ASP 2.0 Service Information Discovery       : Not Supported")
if user_name == "1":print("    IP Docking Capable                          : Not Supported")
if user_name == "1":print("    FIPS                                        : Supported")
if user_name == "1":print("    Instant Connect                             : Supported")
if user_name == "1":print("    Dx Standby NLO                              : Supported")
if user_name == "1":print("    Extended Channel Switch Announcement        : Supported")
if user_name == "1":print("    Function Level Reset                        : Supported")
if user_name == "1":print("    Platform Level Reset                        : Supported")
if user_name == "1":print("    Bus Level Reset                             : Supported")
if user_name == "1":print("    MAC Randomization                           : Supported")
if user_name == "1":print("    Fast Transition                             : Supported")
if user_name == "1":print("    MU-MIMO                                     : Supported")
if user_name == "1":print("    Miracast Sink                               : Supported")
if user_name == "1":print("    BSS Transition (802.11v)                    : Supported")
if user_name == "1":print("    IHV Extensibility Module Configured         : Supported")
if user_name == "1":print("    SAE Authentication                          : Supported")
if user_name == "1":print("    SAE Hash-to-Element Authentication          : Supported")
if user_name == "1":print("    WPA3 SUITE-B Authentication                 : Supported")
if user_name == "1":print("    WPA3 SUITE-B FIPS Mode                      : Not Supported")
if user_name == "1":print("    OWE Authentication                          : Supported")
if user_name == "1":print("    FTM as Initiator                            : Not Supported")
if user_name == "1":print("    MBO Support                                 : Supported")
if user_name == "1":print("    Number of Tx Spatial Streams                : 2")
if user_name == "1":print("    Number of Rx Spatial Streams                : 2")
if user_name == "1":print("    Number of Concurrent Channels Supported     : 0")
if user_name == "1":print("    P2P GO ports count                          : 1")
if user_name == "1":print("    P2P Clients Port Count                      : 1")
if user_name == "1":print("    P2P Max Mobile AP Clients                   : 8")
if user_name == "1":print("    Max ANQP Service Advertisements Supported   : 0")
if user_name == "1":print("    Maximum Number of Secondary STAs supported  : 0")
if user_name == "1":print("    Number of MultiLink Connections supported   : 0")
if user_name == "1":print("    Co-existence Support                        : Wi-Fi performance is maintained")